### ISSUE TITLE
LilyGo T5 4.7inch - eInk  display effect is darker when use library of epdiy,   Compared with lilygo's library

### ISSUE THREAD

**Issue by lixy123** [vroland/epdiy#159] opened 2022-02-18 09:00 UTC
I use the official sample demo example of lilygo T5 47 ink screen library and the epdiy library demo example code, 
and found that the example code in epdiy is slightly dark,  I feel that I didn't do it right everywhere

You can compare  run result of  the two example code Light hearted:
https://github.com/vroland/epdiy/tree/master/examples/lilygo-t5-47-epd-platformio
https://github.com/Xinyuan-LilyGO/LilyGo-EPD47/tree/master/examples/demo

It's dimmed a lot. 
The display effect makes people look unhappy. Can you give me some suggestions

**Comment by vroland** [comment] 2022-02-18 09:42
Could you check if this PR fixes that? https://github.com/vroland/epdiy/pull/158

**Comment by martinberlin** [comment] 2022-02-26 20:54
@lixy123 can you please pull the latest master and try out?
I cannot reproduce this, can you please drop some photos as a response to show this effect you are seeing?

**Comment by martinberlin** [comment] 2022-04-22 18:13
Hi @lixy123 can you please give this a try?
When more than two months pass from the request from feedback I suggest we consider this as a stale Issue and close. Please respond if you want to keep this alive.

**Comment by martinberlin** [comment] 2022-04-23 21:23
Closing here since the same issue is being addressed on https://github.com/vroland/epdiy/issues/171
And it has been also almost 2 months since last request of feedback. Please follow latest pull request for updates since I am quite sure this is related to the new waveform

**Closed by martinberlin** 2022-04-23 21:23 UTC
